baseURL = 'https://macamev.github.io/
languageCode = 'en-us'
title = 'Macamev Foods'
theme = "anubis"
[Author]
    name = "Macamev"
[params]
author = "Macamev"
style = "auto"
body_classes = "helvetica bg-near-white"
post_content_classes = "mono neue"
[taxonomies]
   tag = "tags"
   category = "categories"
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1
[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 2


    
